#include "utl.h"
#include "hstgr_priv.h"

#define hstgr_DEFINE_FUNC_UPDATE_HISTOGRAM(STRG_CLS, BIN_TYPE, INPUT_T, BIN_SIZE_T, GET_BIN_IDX_FUNC)\
    utltype_REF_MACRO_EXP_ARGS(DIRECT_DEFINE_FUNC_UPDATE_HISTOGRAM, STRG_CLS, BIN_TYPE_CC(BIN_TYPE),\
        BIN_TYPE, INPUT_T, utltype_PRFX_LC(INPUT_T), utltype_PRFX_UC(INPUT_T), BIN_SIZE_T,\
        utltype_PRFX_LC(BIN_SIZE_T), utltype_PRFX_UC(BIN_SIZE_T), GET_BIN_IDX_FUNC)

#define hstgr_DEFINE_FUNC_GET_EVEN_BIN_IDX(STRG_CLS, INPUT_T, BIN_SIZE_T)\
    utltype_REF_MACRO_EXP_ARGS(DIRECT_DEFINE_FUNC_GET_EVEN_BIN_IDX, STRG_CLS,\
        INPUT_T, utltype_PRFX_LC(INPUT_T), utltype_PRFX_UC(INPUT_T),\
        BIN_SIZE_T, utltype_PRFX_LC(BIN_SIZE_T), utltype_PRFX_UC(BIN_SIZE_T))

#define hstgr_DEFINE_FUNC_GET_EVEN_BIN_ATTRIB(STRG_CLS, INPUT_T, BIN_SIZE_T)\
    utltype_REF_MACRO_EXP_ARGS(DIRECT_DEFINE_FUNC_GET_EVEN_BIN_ATTRIB, STRG_CLS,\
        INPUT_T, utltype_PRFX_LC(INPUT_T), utltype_PRFX_UC(INPUT_T),\
        BIN_SIZE_T, utltype_PRFX_LC(BIN_SIZE_T), utltype_PRFX_UC(BIN_SIZE_T))

#define hstgr_DEFINE_EVEN_HISTOGRAM(STRG_CLS, INPUT_T, BIN_SIZE_T)\
    hstgr_DEFINE_FUNC_UPDATE_HISTOGRAM(STRG_CLS, EVEN, INPUT_T, BIN_SIZE_T, utltype_REF_MACRO_EXP_ARGS(\
        BUILD_GET_BIN_IDX_FUNC_NAME, Even, utltype_PRFX_LC(INPUT_T), utltype_PRFX_LC(BIN_SIZE_T)))\
    hstgr_DEFINE_FUNC_GET_EVEN_BIN_IDX(STRG_CLS, INPUT_T, BIN_SIZE_T)\
    hstgr_DEFINE_FUNC_GET_EVEN_BIN_ATTRIB(STRG_CLS, INPUT_T, BIN_SIZE_T)


hstgr_DEFINE_FUNC_GET_EVEN_BIN_IDX(, UNSIGNED16, UNSIGNED16)